### ISSUE TITLE
Include TypeScript typings into npm package

### ISSUE THREAD

**Issue by rerezz** [mihaifm/linq#13]
It would be nice to have the typings (https://linqjs.codeplex.com/SourceControl/latest#typescript/) in the npm package.

**Comment by cervengoc** [comment]
@mihaifm First of all thank you for keeping this library alive. It's been a long time in this issue, but I'd like to  say that the typings file is still not in the NPM package for some reason. 

Also, the TypeScript 2.0 module resolution logic needs that the typings file is referenced in the `package.json` file, please see this related documentation here http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

And last but not least, in the typings file itself some modifications should me made to make it work nicely in the TypeScript module system. For this latter I can probably put together a PR if you're open to that.

I'd really appreciate if you could make these technical improvements and release a new NPM package. thank you in advance.

**Comment by mihaifm** [comment]
Hi

I've only recently included the typings to the source code, but haven't published to npm yet. 

Thanks for pointing out these issues. My experience with Typescript is minimal, so I would appreciate a pull request, if you have the time. 
Otherwise, I will look into them when I get the chance.

thanks

**Comment by mihaifm** [comment]
Thanks for your help. A new version has been published to npm.
